# Generated by Django 5.2.4 on 2025-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weblink', models.URLField(max_length=500)),
                ('data', models.TextField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
